spring.application.name=salesmanagement
spring.datasource.url=jdbc:mysql://localhost:3306/salesmanagement
spring.datasource.username=root
spring.datasource.password=1031
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.jerry.salesmanagement.pojo

server.port=8081
server.address=localhost
server.servlet.session.timeout = 900
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2MB
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
app.attachment.storage-root=uploads
app.pdf.font-path=
